### PR TITLE
simpler/more efficient interleaving for up_conv

### PR DESCRIPTION
**Pull request by jtatusko**
time comparison on a single image (inference):
Elapsed time for run: 0:00:02.076628 (pack + reshape)
Elapsed time for run: 0:00:02.555231 (dynamic stitch)

disclaimers:
* I ran on a CPU instead of a GPU, so it's probably worth testing that.
* I included the timing code so you guys know what I did to time it (just wrapped the session.run)
* I included a get_incoming_shape since I just felt like lists with integers are easier to deal with than tensorflow's Dimension stuff.
* Also added code to display the input image. Thought it would be nice to compare.

### CODE REVIEW

**Comment by jtatusko** [comment]
Sure, no problem. I would be curious to see if adding lateral connections from the down-sampling network to the up-sampling part of the network would improve accuracy (https://arxiv.org/pdf/1612.03144v1.pdf). I might test that out if I have time

**Comment by vinthony** [comment]
@jtatusko hi,  do you test the result of add the connection between down-sampling network and up-sampling part?

**Comment by NikolausDemmel** [comment]
@jtatusko, does the same model (http://campar.in.tum.de/files/rupprecht/depthpred/NYU_ResNet-UpProj.npy) still work with this change?

**Comment by iro-cp** [comment]
Thanks again for your feedback! We have now integrated your suggestion regarding a more efficient interleaving layer - without the use of variables - into the master branch

**Pull request closed without merging**
